openapi: 3.0.1
info:
  title: NodeJs Challenge 20200902
  description: CRUD Products
  version: '0.1'

  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  production:
    url: 'https://url_production'
    protocol: https
    description: >-
      url from production, no tokens or ApiKey will be used.
  development:
    url: 'http://url_development'
    protocol: https
    description: >-
      url from develoment, no tokens or ApiKey will be used.
    variables:
      port:
        description: Connection port.
        default: '3000'
defaultContentType: application/json